do not use file dependency
use flatDir instead,
fix java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase
agp has a bug and dose not intend to fix it,
library module use file dependency cause desugar failed,
https://issuetracker.google.com/issues/183632445